// Small-port harness for Stage3 lifecycle proofs. Data/tag SRAM values are
// fixed because only response control is in scope; hit/miss, dirty-victim,
// downstream-ready and memory/MMIO progress remain symbolic inputs.
module CacheStage3LifecycleHarness(
  input clock,
  input reset,
  input request_valid,
  input [3:0] request_cmd,
  input request_hit,
  input request_mmio,
  input victim_dirty,
  input response_ready,
  input mem_req_ready,
  input mem_resp_valid,
  input [3:0] mem_resp_cmd,
  input mmio_req_ready,
  input mmio_resp_valid,
  output response_valid,
  output [3:0] response_cmd,
  output is_finish
);
  CacheStage3 dut (
    .clock(clock),
    .reset(reset),
    .io_in_ready(),
    .io_in_valid(request_valid),
    .io_in_bits_req_addr(32'b0),
    .io_in_bits_req_size(3'd3),
    .io_in_bits_req_cmd(request_cmd),
    .io_in_bits_req_wmask(8'hff),
    .io_in_bits_req_wdata(64'b0),
    .io_in_bits_req_user(16'b0),
    .io_in_bits_metas_0_tag(19'b0),
    .io_in_bits_metas_0_dirty(victim_dirty),
    .io_in_bits_metas_1_tag(19'b0),
    .io_in_bits_metas_1_dirty(1'b0),
    .io_in_bits_metas_2_tag(19'b0),
    .io_in_bits_metas_2_dirty(1'b0),
    .io_in_bits_metas_3_tag(19'b0),
    .io_in_bits_metas_3_dirty(1'b0),
    .io_in_bits_datas_0_data(64'b0),
    .io_in_bits_datas_1_data(64'b0),
    .io_in_bits_datas_2_data(64'b0),
    .io_in_bits_datas_3_data(64'b0),
    .io_in_bits_hit(request_hit),
    .io_in_bits_waymask(4'b0001),
    .io_in_bits_mmio(request_mmio),
    .io_in_bits_isForwardData(1'b0),
    .io_in_bits_forwardData_data_data(64'b0),
    .io_in_bits_forwardData_waymask(4'b0),
    .io_out_ready(response_ready),
    .io_out_valid(response_valid),
    .io_out_bits_cmd(response_cmd),
    .io_out_bits_rdata(),
    .io_out_bits_user(),
    .io_isFinish(is_finish),
    .io_flush(1'b0),
    .io_dataReadBus_req_ready(1'b1),
    .io_dataReadBus_req_valid(),
    .io_dataReadBus_req_bits_setIdx(),
    .io_dataReadBus_resp_data_0_data(64'b0),
    .io_dataReadBus_resp_data_1_data(64'b0),
    .io_dataReadBus_resp_data_2_data(64'b0),
    .io_dataReadBus_resp_data_3_data(64'b0),
    .io_dataWriteBus_req_valid(),
    .io_dataWriteBus_req_bits_setIdx(),
    .io_dataWriteBus_req_bits_data_data(),
    .io_dataWriteBus_req_bits_waymask(),
    .io_metaWriteBus_req_valid(),
    .io_metaWriteBus_req_bits_setIdx(),
    .io_metaWriteBus_req_bits_data_tag(),
    .io_metaWriteBus_req_bits_data_dirty(),
    .io_metaWriteBus_req_bits_waymask(),
    .io_mem_req_ready(mem_req_ready),
    .io_mem_req_valid(),
    .io_mem_req_bits_addr(),
    .io_mem_req_bits_cmd(),
    .io_mem_req_bits_wdata(),
    .io_mem_resp_ready(),
    .io_mem_resp_valid(mem_resp_valid),
    .io_mem_resp_bits_cmd(mem_resp_cmd),
    .io_mem_resp_bits_rdata(64'b0),
    .io_mmio_req_ready(mmio_req_ready),
    .io_mmio_req_valid(),
    .io_mmio_req_bits_addr(),
    .io_mmio_req_bits_size(),
    .io_mmio_req_bits_cmd(),
    .io_mmio_req_bits_wmask(),
    .io_mmio_req_bits_wdata(),
    .io_mmio_resp_ready(),
    .io_mmio_resp_valid(mmio_resp_valid),
    .io_mmio_resp_bits_rdata(64'b0),
    .io_cohResp_ready(1'b1),
    .io_cohResp_valid(),
    .io_cohResp_bits_cmd(),
    .io_cohResp_bits_rdata(),
    .io_dataReadRespToL1()
  );
endmodule
